### ISSUE TITLE
DSM Says an update is avaible

### ISSUE THREAD

**Issue by Meteo07** [reidemei/synology-autorun#23]
DSM 6 says an update is avaible, can you make a 1.7 version, but with 1.8 numeber for bypass update please?

**Comment by geimist** [comment]
You can fix this yourself:
1. stop autorun
2. run this command as root (e.g. at TaskManger in DSM or via SSH) 
```synosetkeyvalue /var/packages/autorun/INFO version "1.8"```
3. start autorun

**Comment by Meteo07** [comment]
Hi, nice, working well thanks

 

La Météo en direct de Bourg-Saint-Andéol

 

 

You can fix this yourself:
stop autorun
run this command as root (e.g. at TaskManger in DSM)
synosetkeyvalue /var/packages/autorun/INFO version "1.8"
start autorun
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by reidemei** [comment]
This is a limitation of https://www.cphub.net/ which does not support different versions for different DSM. So only the latest DSM will work from there. Nothing I can do here.
